aws_region = "ap-northeast-1"
vpc_cidr   = "10.123.0.0/16"
key_name   = "galaxy-demo-TAJ"
#public_key_path = "/home/ubuntu/.ssh/demo-devops-cloud-taj.pub"
public_key_path = "C:\\Users\\Administrator\\.ssh\\id_rsa.pub"